load("@rules_cuda//cuda:defs.bzl", "cuda_library", "cuda_test")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_test")

package(default_visibility = ["//visibility:public"])

# CUDA Math library
cuda_library(
    name = "matrix",
    srcs = ["matrix.cu"],
    hdrs = ["matrix.cuh"],
)

# Vector addition kernel
cuda_library(
    name = "vector_add_kernel",
    srcs = ["kernel.cu"],
    hdrs = ["matrix.cuh"],
    deps = [
        ":matrix",
    ],
)

# Test suite
cuda_test(
    name = "matrix_test",
    srcs = ["matrix_test.cu"],
    deps = [
        ":matrix",
        ":vector_add_kernel",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
